"""

This file is injected in _boot.py during the build
meaning whatever is defined here will run right after the normal _boot.py
generated by MicroPython make, and you do not need to define a main.py at all

"""


from time import sleep, sleep_ms

print("hi")
