#
# M5Stick-C specific
#

#EXTMOD_SRC_C += \
	m5stickc.c \
	util/AXP192.c \
	util/MPU6886.c \
	util/button.c \
	util/font/DefaultFont.c \
	util/font/DejaVuSans18.c \
	util/font/DejaVuSans24.c \
	util/font/SmallFont.c \
	util/font/Ubuntu16.c \
	util/font/comic24.c \
	util/font/default_tiny_9pt.c \
	util/font/def_small.c \
	util/font/minya24.c \
	util/font/tooney32.c \
	util/i2smic.c \
	util/spi_master_lobo.c \
	util/tft.c \
	util/tftspi.c \
	util/wire.c

#ST77XX_MOD_DIR := st77xx
#SRC_C += $(addprefix $(ST77XX_MOD_DIR)/, st77xx.c)
#CFLAGS += -I$(ST77XX_MOD_DIR) -DMODULE_ST77XX_ENABLED=1 -DST77XX_EXPOSE_EXTRA_METHODS=1
#OBJ_MP += $(addprefix $(ST77XX_MOD_DIR)/, st77xx.c)
#OBJ += $(OBJ_MP)
#SRC_QSTR += $(addprefix $(ST77XX_MOD_DIR)/, st77xx.c)
#SRC_QSTR_AUTO_DEPS +=

#OBJ_MP += $(addprefix $(BUILD)/, $(EXTMOD_SRC_C:.c=.o))
#OBJ += $(OBJ_MP)
#SRC_QSTR += $(EXTMOD_SRC_C)
#SRC_QSTR_AUTO_DEPS +=

include st77xx/micropython.mk

CONFIG_SPIRAM_BOOT_INIT=y
CONFIG_SPIRAM_IGNORE_NOTFOUND=y
CONFIG_SPIRAM_USE_MEMMAP=
CONFIG_SPIRAM_USE_CAPS_ALLOC=y
CONFIG_SPIRAM_USE_MALLOC=
CONFIG_SPIRAM_TYPE_ESPPSRAM32=y
CONFIG_SPIRAM_SIZE=4194304
CONFIG_SPIRAM_SPEED_40M=y
CONFIG_SPIRAM_MEMTEST=y
CONFIG_SPIRAM_CACHE_WORKAROUND=y
CONFIG_WIFI_LWIP_ALLOCATION_FROM_SPIRAM_FIRST=y
CONFIG_MEMMAP_TRACEMEM=
CONFIG_MEMMAP_TRACEMEM_TWOBANKS=
CONFIG_ESP32_TRAX=
CONFIG_TRACEMEM_RESERVE_DRAM=0x0

#CONFIG_ESPTOOLPY_FLASHFREQ_40M=y
#CONFIG_SPIRAM_SPEED_80M=y
CONFIG_FLASHMODE_QIO=y
#CONFIG_ESP32_REV_MIN_1=y

CONFIG_LOG_BOOTLOADER_LEVEL_INFO=y

CONFIG_LWIP_L2_TO_L3_COPY=y 
CONFIG_LWIP_SO_REUSE=y
CONFIG_LWIP_SO_REUSE_RXTOALL=y
CONFIG_LWIP_IP_FRAG=y
CONFIG_LWIP_IP_FORWARD=y
CONFIG_LWIP_IPV4_NAPT=y
CONFIG_LWIP_ESP_GRATUITOUS_ARP=y
CONFIG_LWIP_ESP_LWIP_ASSERT=y

CONFIG_MBEDTLS_SHA512_C=y
