
ST77XX_MOD_DIR := $(USER_C_MODULES)
SRC_USERMOD += $(addprefix $(ST77XX_MOD_DIR)/, \
	st77xx.c \
)
CFLAGS_USERMOD += -I$(ST77XX_MOD_DIR) -DMODULE_ST77XX_ENABLED=1 -DST77XX_EXPOSE_EXTRA_METHODS=1

OBJ_MP += $(addprefix $(ST77XX_MOD_DIR)/, st77xx.c)
OBJ += $(OBJ_MP)
SRC_QSTR += $(addprefix $(ST77XX_MOD_DIR)/, st77xx.c)
SRC_QSTR_AUTO_DEPS +=
